name: pvpstats
main: net.slipcor.pvpstats.PVPStats
version: 1.7.40
api-version: 1.13
author: slipcor
softdepend: [pvparena,PlaceholderAPI]
website: https://www.spigotmc.org/resources/pvp-stats.59124/
commands:
  pvpstats:
    description: handle PvP stats
    aliases: stats
permissions:
  pvpstats.reload:
    description: Ability to reload
    default: op
  pvpstats.cleanup:
    description: Ability to cleanup
    default: op
  pvpstats.config:
    description: Ability to read and alter config values
    default: op
  pvpstats.migrate:
    description: Ability to migrate
    default: op
  pvpstats.purge:
    description: Ability to purge
    default: op
  pvpstats.wipe:
    description: Ability to wipe
    default: op
  pvpstats.debug:
    description: Ability to debug
    default: op
  pvpstats.debugkill:
    description: Ability to add a debug kill
    default: op
  pvpstats.count:
    description: Permission to be counted
    default: true
  pvpstats.nonewbie:
    description: Permission to be out of newbie status
    default: true
  pvpstats.newbie:
    description: Permission to be not out of newbie status
    default: false
  pvpstats.top:
    description: Permission to get global stats
    default: true
  pvpstats.null:
    description: Permission that you should not give to anyone.
    default: false
  pvpstats.opmessages:
    description: Permission to notify when the plugin errors
    default: op