name: pvpstats
main: net.slipcor.pvpstats.PVPStats
version: 0.8.21
author: slipcor
softdepend: [pvparena, PlaceholderAPI]
website: http://dev.bukkit.org/server-mods/pvp-stats/
commands:
    pvpstats:
        description: handle PvP stats
        aliases: stats
permissions:
    pvpstats.reload:
        description: Ability to reload
        default: op
    pvpstats.cleanup:
        description: Ability to cleanup
        default: op
    pvpstats.purge:
        description: Ability to purge
        default: op
    pvpstats.wipe:
        description: Ability to wipe
        default: op
    pvpstats.count:
        description: Permission to be counted
        default: true
    pvpstats.top:
        description: Permission to get global stats
        default: true
